config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}
  devise_for :shops, controllers: {
    registrations: 'shops/registrations'
  }

  root to: 'shops#index'
  get 'about' => 'homes#about'
  resources :shops, only: [:index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create]
  end
  resources :foods, only: [:new, :create, :edit, :update, :destroy, :show]

  namespace :admins do
    resources :shops, only: [:index, :show, :destroy]
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  belongs_to :genre, dependent: :destroy

  attachment :shop_image

  validates :shop_name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :login_id, presence: true


  def current_shop?(current_shop)
    self == current_shop
  end

  def self.search(search,genre_id,admin) #self.でクラスメソッドとしている
    if admin
     if search.blank?
        all
     else
       keyword(search)
     end
    else
      if search.blank? && genre_id.blank? #両方空の場合
         order("RAND()").all #全てランダムで表示。
      elsif search.empty? #searchが空でジャンルのみの検索
         where(genre_id: genre_id)
      elsif genre_id.blank? #ジャンルが空の場合
         keyword(search)
      else #両方有りの場合
         keyword(search).where(genre_id: genre_id)
      end
    end
  end

  def self.keyword(search)
   where(['phone_number LIKE(?) OR address LIKE(?) OR shop_name LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%"]) #where(['検索したいカラム名 ? OR 検索したいカラム名 LIKE ? OR 検索したいカラム名 LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
  end


  def save_notification_comment!(comment_id)
        notification = notifications.new(
        shop_id: id,
        comment_id: comment_id,
        action: 'comment'
      )
      notification.save if notification.valid?
  end

end

app/controllers/admins/shops_controller.rb
class Admins::ShopsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @shops = Shop.search(params[:search],nil,true)
  end
  def show
    @shop = Shop.find(params[:id])
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to admins_shops_path
  end
end

app/controllers/shops/confirmations_controller.rb
# frozen_string_literal: true

class Shops::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shops/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Shops::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/shops/passwords_controller.rb
# frozen_string_literal: true

class Shops::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shops/registrations_controller.rb
# frozen_string_literal: true

class Shops::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_sign_up_path_for(resource)
    edit_shop_path(resource)
  end
end

app/controllers/shops/sessions_controller.rb
# frozen_string_literal: true

class Shops::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/shops/unlocks_controller.rb
# frozen_string_literal: true

class Shops::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
 before_action :authenticate_shop!, except: [:show, :index]
  def index
    @shops = Shop.search(params[:search],params[:genre_id],false).page(params[:page]).reverse_order
  end

  def show
    @shop = Shop.find(params[:id])
    @foods = @shop.foods.all
    @comment = Comment.new
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shop_path(current_shop)
    else
      redirect_to edit_shop_path(current_shop)
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to root_path
  end

  private

  def shop_params
    params.require(:shop).permit(:shop_name, :shop_image, :address, :phone_number, :holiday, :introduction, :opening_hours1, :opening_hours2, :genre_id)
  end

end

app/helpers/admins/shops_helper.rb
module Admins::ShopsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
  def unchecked_notifications
    @notifications = current_shop.notifications.where(checked: false)
  end
end

app/views/shops/edit.html.slim
.container
  .row.mt-5
    .col-5.mx-auto
      - if @shop.errors.any?
        .error
          | #{@shop.errors.count} 件の入力ミス

      = form_with model:@shop, local:true do |f|
          .field
            = f.label "お店名(必須)"
            br
            = f.text_field :shop_name
          .field.mt-3
            = f.label "お店の画像"
            br
            = f.attachment_field :shop_image
            br
          .field.mt-3
            = f.label "お店の電話番号(必須)"
            br
            = f.text_field :phone_number
          .field.mt-3
            = f.label "ジャンル(必須)"
            br
            = f.collection_select :genre_id, Genre.all,:id, :genre_name, include_blank: "--選択してください--"
            /form.collection_select(保存されるカラム名, オブジェクトの配列, カラムに保存される項目, 選択肢に表示されるカラム名

          .field.mt-3
            = f.label "紹介文"
            br
            = f.text_area :introduction
          .field.mt-3
            = f.label "営業時間(必須)"
            br
            p #{f.text_field :opening_hours1}時から
              #{f.text_field :opening_hours2}時

          .field.mt-3
            = f.label "定休日(必須)"
            br
            = f.text_field :holiday

          .field.mt-3
            = f.submit "変更する", class: "btn btn-success"
            br
            .mt-3 = link_to "退会する", shop_path(current_shop.id), method: :delete, data: { confirm: '退会しますか？' }, class: "btn btn-danger"

app/views/shops/index.html.slim
.container
  .row.mt-1
    .col-12.text-center.top-img = image_tag('img/topp.png', :size =>'800x300')
  .row
    .col-4.mt-5
      = form_with url: shops_path, method: :get do |f|
        h5
          | キーワード検索

        p
          | (住所や店名)

        = f.text_field :search, placeholder: "◯◯県◯◯市など、、"
        br
        .mt-3
          = f.collection_select :genre_id, Genre.all,:id, :genre_name, include_blank: "ジャンル"
        br
        = f.submit '検索'

    .col-7.mt-4
      h2.ml-5
              | お店一覧

      .text-center
          .mx-auto
            table.mt-5.mb-5
                - @shops.each do |shop|
                    tr.mb-5
                      td = link_to shop_path(shop.id) do
                          = attachment_image_tag(shop, :shop_image, :fill, 250, 200, fallback: 'img/no_image.png', class: 'index_shop_image')
                      td
                        table.table
                          tr
                            td = link_to shop_path(shop.id), class: 'text-dark' do
                              .h4 = shop.shop_name
                          tr
                            td = shop.address
                          tr
                            td = shop.phone_number

            .h4.ml-5 = paginate @shops

app/views/shops/show.html.slim
.container
  .row.mt-5
    .col-5
      .text-center = attachment_image_tag(@shop, :shop_image, fallback: 'img/no_image.png', class: 'show_shop_image')
    .col-4.ml-5
      h2.text-center.mt-4.font-weight-bold
        |・#{@shop.shop_name}

      br
      .h2.text-center = link_to @shop.phone_number, "tel:" + @shop.phone_number
      br
      .col-10.ml-5
        .card
          .pt-2 = @shop.introduction
          br
        .card.mt-3
          .mt-2
            | 住所 : #{@shop.address}

            br

            | 営業時間 : #{@shop.opening_hours1}時~#{@shop.opening_hours2}時

            br

            | 定休日 : #{@shop.holiday}

        br
      .mt-2
      - if @shop.current_shop?(current_shop)
        .text-center
          = link_to "お店情報編集", edit_shop_path(@shop), class: "mr-2 btn btn-secondary"
          = link_to "メニュー追加", new_food_path, class: "btn btn-secondary"

        .mt-2.ml-5 = link_to "コメント一覧", shop_comments_path(@shop), class: "btn btn-outline-info"
        - if unchecked_notifications.any?
          p.unchecked-text
            | 新着コメントがあります！

      - else
        .text-center.ml-2.mt-1 = form_with(model:[@shop, @comment], local: true) do |f|
          = f.label "お店にコメント"
          br
          = f.text_area :body, rows:'2',placeholder: "よろしければ、料理の感想などお願いします。"
          = f.hidden_field :shop_id, :value => @shop.id
          br
          = f.submit "送信する"
        - if flash[:notice]
          .flash = flash[:notice]
        - else flash[:alert]
          .alert = flash[:alert]
  .row.mt-5
    .col-12
      table.table
        thead
          tr
            th
            th 料理名
            th 値段(税込)
            - if @shop.current_shop?(current_shop)
              th
              th
        tbody
        - @foods.each do |food|
          tr.h5
            td = link_to food_path(food.id) do
                = attachment_image_tag food, :food_image, :fill, 60, 60
            td = link_to food_path(food.id), class: 'text-dark' do
                .mt-3 = food.food_name
            td
              .mt-3 #{(food.price * 1.1).floor} 円
            - if @shop.current_shop?(current_shop)
              td
                .mt-3 = link_to "削除", food_path(food.id), method: :delete, data: { confirm: '削除しますか？' }, class: "btn btn-danger"

              td
                .mt-3 = link_to "編集", edit_food_path(food.id), class: "btn btn-success"