config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}
  devise_for :shops, controllers: {
    registrations: 'shops/registrations'
  }

  root to: 'shops#index'
  get 'about' => 'homes#about'
  resources :shops, only: [:index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create]
  end
  resources :foods, only: [:new, :create, :edit, :update, :destroy, :show]

  namespace :admins do
    resources :shops, only: [:index, :show, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :shop
  has_many :notifications, dependent: :destroy

  validates :body, presence: true

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :shop
  has_many :tags
  attachment :food_image

  validates :food_image, presence: true
  validates :food_name, presence: true
  validates :price, presence: true

  def create_tags!
    tags.destroy_all if tags.present?

    image_tags = Vision.get_image_data(food_image)
    image_tags.each do |tag|
      tags.create(name: tag)
    end

  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shops, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) } #デフォルトの並び順を「作成日時の降順」で指定(常に新しい通知からデータを取得することができる)
  belongs_to :shop
  belongs_to :comment

  scope :unchecked, -> { where(checked: false) }
  def self.checked!
    unchecked.each { |notification| notification.update!(checked: true) }
  end

end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  belongs_to :genre, dependent: :destroy

  attachment :shop_image

  validates :shop_name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :login_id, presence: true


  def current_shop?(current_shop)
    self == current_shop
  end

  def self.search(search,genre_id,admin) #self.でクラスメソッドとしている
    if admin
     if search.blank?
        all
     else
       keyword(search)
     end
    else
      if search.blank? && genre_id.blank? #両方空の場合
         order("RAND()").all #全てランダムで表示。
      elsif search.empty? #searchが空でジャンルのみの検索
         where(genre_id: genre_id)
      elsif genre_id.blank? #ジャンルが空の場合
         keyword(search)
      else #両方有りの場合
         keyword(search).where(genre_id: genre_id)
      end
    end
  end

  def self.keyword(search)
   where(['phone_number LIKE(?) OR address LIKE(?) OR shop_name LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%"]) #where(['検索したいカラム名 ? OR 検索したいカラム名 LIKE ? OR 検索したいカラム名 LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
  end


  def save_notification_comment!(comment_id)
        notification = notifications.new(
        shop_id: id,
        comment_id: comment_id,
        action: 'comment'
      )
      notification.save if notification.valid?
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:shop_name, :address, :phone_number, :login_id, :email, :encrypted_password])
  end

  def after_sign_in_path_for(resource)
    shop_path(resource)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @shop = current_shop
    @comments = @shop.comments.order(created_at: :desc).page(params[:page]).per(10)
    # 新しい順に１０ずつ表示
    @notifications = current_shop.notifications
    @notifications.checked!
  end

  def create
    @shop = Shop.find(params[:shop_id])
    #投稿に紐づいたコメントを作成
    @comment = @shop.comments.new(comment_params)
    if @comment.save
      #通知の作成
      @shop.save_notification_comment!(@comment.id)
      flash[:notice] = "コメントを送信しました!"
      redirect_to shop_path(@comment.shop.id)
    else
      flash.now[:alert] = "文字を入力して下さい"
      redirect_to shop_path(@comment.shop.id)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :shop_id)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
 before_action :authenticate_shop!, except: [:show]
  def new
    @food = Food.new
  end

  def create
    food = Food.new(food_parms)
    food.shop_id = current_shop.id
    if food.save
      food.create_tags!
      redirect_to shop_path(current_shop)
    else
      render :new
    end
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    food = Food.find(params[:id])
    if food.update(food_parms)
      food.create_tags!
      redirect_to shop_path(current_shop)
    else
      render :edit
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    redirect_to shop_path(current_shop)
  end

  private

  def food_parms
     params.require(:food).permit(:food_name, :introduction, :food_image, :price, :shop_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
 before_action :authenticate_shop!, except: [:show, :index]
  def index
    @shops = Shop.search(params[:search],params[:genre_id],false).page(params[:page]).reverse_order
  end

  def show
    @shop = Shop.find(params[:id])
    @foods = @shop.foods.all
    @comment = Comment.new
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shop_path(current_shop)
    else
      redirect_to edit_shop_path(current_shop)
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to root_path
  end

  private

  def shop_params
    params.require(:shop).permit(:shop_name, :shop_image, :address, :phone_number, :holiday, :introduction, :opening_hours1, :opening_hours2, :genre_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
  def unchecked_notifications
    @notifications = current_shop.notifications.where(checked: false)
  end
end

app/views/admins/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/admins/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post
    br

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TelTake
    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    header
      .shadow-sm
        .navbar.navbar-expand-lg.navbar-light
          .container
            .navbar-brand
              = link_to root_path do
                = image_tag('img/logo.png', :size =>'160x90')


            .navbar.ml-auto.h5
              - if shop_signed_in?
                .nav-item = link_to "ログアウト", destroy_shop_session_path, method: :delete, class: 'nav-link text-dark'
                .nav-item = link_to "マイページ", shop_path(current_shop.id), class: 'nav-link text-dark'
              - else
                .nav-item = link_to "お店管理", new_shop_session_path, class: 'nav-link text-dark'
              .nav-item = link_to "お問い合わせ", about_path, class: 'nav-link text-dark'
    .main
      = yield

    footer